# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a27b19dc7142301dcc81933a1acb71989b614bf63be4e9c77e1ab28309a945eaad5bb07f29547255f4faf7afaabae08d05cdcf173e95d7885dbd09a1be02e23

test:
  secret_key_base: 048e42f329ced60d9d7ce425cf0d327cedf907b696880934317df7a5147ddce661d748814c6c8ac0fddf9557552de8c285dba37a76e04204cfd64d9fdf29aa89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
